name: Azure QA Deploy

on:
  push:
    branches:
      - azure-qa
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build-qa --if-present

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AZURE_QA_SSH_USER }}
          SSH_KEY: ${{ secrets.AZURE_QA_SSH_KEY }}
          SSH_HOST: ${{ secrets.AZURE_QA_SSH_HOST }}

      - name: Copy Release to Remote
        run: |
          scp -o StrictHostKeyChecking=no -r -i ~/.ssh/id_rsa dist/mango-angular-frontend/* $SSH_USER@$SSH_HOST:/home/$SSH_USER/dist/mango-angular-frontend
          scp -o StrictHostKeyChecking=no -r -i ~/.ssh/id_rsa dist/mango-angular-frontend/index.html $SSH_USER@$SSH_HOST:/home/$SSH_USER/dist/mango-angular-frontend/404.html
        env:
          SSH_USER: ${{ secrets.AZURE_QA_SSH_USER }}
          SSH_HOST: ${{ secrets.AZURE_QA_SSH_HOST }}

      - name: Restart nginx
        run: ssh staging "sudo systemctl restart nginx"
